import { renderCanonicalSourceList } from '../core/managed-files.js';

export function renderManagedFileHeader({ agent, canonicalSources, regenerateCommand }) {
  return [
    '<!--',
    'Generated by Prodify.',
    `Target agent: ${agent}`,
    `Canonical source: ${renderCanonicalSourceList(canonicalSources)}`,
    `Regenerate with: ${regenerateCommand}`,
    'Manual edits may be overwritten.',
    '-->'
  ].join('\n');
}
