import { renderCanonicalSourceList } from '../core/managed-files.js';
import type { RuntimeProfileName } from '../types.js';

export function renderManagedFileHeader({
  agent,
  canonicalSources,
  regenerateCommand,
  bodyFingerprint
}: {
  agent: RuntimeProfileName;
  canonicalSources: readonly string[];
  regenerateCommand: string;
  bodyFingerprint: string;
}): string {
  return [
    '<!--',
    'Generated by Prodify.',
    `Target agent: ${agent}`,
    `Canonical source: ${renderCanonicalSourceList(canonicalSources)}`,
    `Regenerate with: ${regenerateCommand}`,
    `Body fingerprint: ${bodyFingerprint}`,
    'Manual edits may be overwritten.',
    '-->'
  ].join('\n');
}
