import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';

import { runCli } from '../../src/cli.js';
import { createTempRepo, memoryStream } from '../unit/helpers.js';

const TARGET_PATHS = {
  codex: 'AGENTS.md',
  claude: 'CLAUDE.md',
  copilot: '.github/copilot-instructions.md',
  opencode: '.opencode/AGENTS.md'
};

async function execCli(repoRoot, args) {
  const stdout = memoryStream();
  const stderr = memoryStream();
  const exitCode = await runCli(args, { cwd: repoRoot, stdout, stderr });

  return {
    exitCode,
    stdout: stdout.toString(),
    stderr: stderr.toString()
  };
}

async function writeCanonical(repoRoot, relativePath, content) {
  await fs.writeFile(path.join(repoRoot, relativePath), content, 'utf8');
}

test('codex full flow works end to end', async () => {
  const repoRoot = await createTempRepo();

  let result = await execCli(repoRoot, ['init']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /Initialized Prodify/);
  await assert.rejects(fs.access(path.join(repoRoot, 'AGENTS.md')));

  result = await execCli(repoRoot, ['install', '--agent', 'codex']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /installed codex: updated .*AGENTS\.md/);
  assert.match(await fs.readFile(path.join(repoRoot, 'AGENTS.md'), 'utf8'), /Generated by Prodify\./);

  await writeCanonical(repoRoot, '.prodify/AGENTS.md', '# Updated Canonical\n');
  result = await execCli(repoRoot, ['sync']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /sync codex: updated .*AGENTS\.md/);

  result = await execCli(repoRoot, ['doctor']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /canonical: PASS/);
  assert.match(result.stdout, /compatibility\/codex: PASS/);
  assert.match(result.stdout, /drift\/AGENTS\.md: PASS/);
});

test('install blocks unmanaged target files for every target family', async () => {
  for (const [agent, relativeTargetPath] of Object.entries(TARGET_PATHS)) {
    const repoRoot = await createTempRepo();
    await execCli(repoRoot, ['init']);
    await fs.mkdir(path.dirname(path.join(repoRoot, relativeTargetPath)), { recursive: true });
    await fs.writeFile(path.join(repoRoot, relativeTargetPath), '# unmanaged\n', 'utf8');

    const result = await execCli(repoRoot, ['install', '--agent', agent]);

    assert.equal(result.exitCode, 1, `expected install failure for ${agent}`);
    assert.match(result.stderr, /not Prodify-managed/);
  }
});

test('managed manual edits block sync until --force is used', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);
  await execCli(repoRoot, ['install', '--agent', 'codex']);
  await writeCanonical(repoRoot, '.prodify/AGENTS.md', '# Canonical Changed\n');

  const targetPath = path.join(repoRoot, 'AGENTS.md');
  const drifted = (await fs.readFile(targetPath, 'utf8')).replace('Prodify Canonical Instructions', 'Manual Edit');
  await fs.writeFile(targetPath, drifted, 'utf8');

  let result = await execCli(repoRoot, ['sync']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /sync codex: blocked .*AGENTS\.md/);

  result = await execCli(repoRoot, ['sync', '--force']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /sync codex: updated .*AGENTS\.md/);
  assert.match(await fs.readFile(targetPath, 'utf8'), /# Canonical Changed/);
});

test('sync stays idempotent and reports unchanged targets', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);
  await execCli(repoRoot, ['install', '--agent', 'codex']);

  const before = await fs.readFile(path.join(repoRoot, 'AGENTS.md'), 'utf8');
  const result = await execCli(repoRoot, ['sync']);
  const after = await fs.readFile(path.join(repoRoot, 'AGENTS.md'), 'utf8');

  assert.equal(result.exitCode, 0);
  assert.equal(before, after);
  assert.match(result.stdout, /sync codex: unchanged .*AGENTS\.md/);
});

test('doctor distinguishes malformed version and drifted managed files', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);
  await execCli(repoRoot, ['install', '--agent', 'codex']);

  await writeCanonical(repoRoot, '.prodify/version.json', '{bad json\n');
  const targetPath = path.join(repoRoot, 'AGENTS.md');
  const drifted = (await fs.readFile(targetPath, 'utf8')).replace('Prodify Canonical Instructions', 'Drifted Body');
  await fs.writeFile(targetPath, drifted, 'utf8');

  const result = await execCli(repoRoot, ['doctor']);

  assert.equal(result.exitCode, 1);
  assert.match(result.stdout, /canonical\/version: FAIL/);
  assert.match(result.stdout, /drift\/AGENTS\.md: FAIL/);
});

test('claude full flow works', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  let result = await execCli(repoRoot, ['install', '--agent', 'claude']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /installed claude \(planned\): updated .*CLAUDE\.md/);
  assert.match(await fs.readFile(path.join(repoRoot, 'CLAUDE.md'), 'utf8'), /Generated by Prodify\./);

  await writeCanonical(repoRoot, '.prodify/AGENTS.md', '# Claude Canonical\n');
  result = await execCli(repoRoot, ['sync']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /sync claude: updated .*CLAUDE\.md/);

  result = await execCli(repoRoot, ['doctor']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /compatibility\/claude: PASS/);
});

test('copilot full flow uses both canonical sources', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  let result = await execCli(repoRoot, ['install', '--agent', 'copilot']);
  assert.equal(result.exitCode, 0);

  const copilotPath = path.join(repoRoot, '.github', 'copilot-instructions.md');
  let content = await fs.readFile(copilotPath, 'utf8');
  assert.match(content, /Generated by Prodify\./);
  assert.match(content, /Project Context/);
  assert.match(content, /Operating Guidance/);

  await writeCanonical(repoRoot, '.prodify/project.md', '# Project\n\nUpdated project context.\n');
  result = await execCli(repoRoot, ['sync']);
  assert.equal(result.exitCode, 0);

  content = await fs.readFile(copilotPath, 'utf8');
  assert.match(content, /Updated project context/);

  result = await execCli(repoRoot, ['doctor']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /compatibility\/copilot: PASS/);
});

test('opencode full flow works at the documented path', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  let result = await execCli(repoRoot, ['install', '--agent', 'opencode']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /installed opencode \(experimental\): updated .*\.opencode\/AGENTS\.md/);
  assert.match(await fs.readFile(path.join(repoRoot, '.opencode', 'AGENTS.md'), 'utf8'), /Generated by Prodify\./);

  await writeCanonical(repoRoot, '.prodify/AGENTS.md', '# OpenCode Canonical\n');
  result = await execCli(repoRoot, ['sync']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /sync opencode: updated .*\.opencode\/AGENTS\.md/);

  result = await execCli(repoRoot, ['doctor']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /compatibility\/opencode: PASS/);
});

test('doctor reports not-installed targets clearly after init only', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  const result = await execCli(repoRoot, ['doctor']);

  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /compatibility\/codex: SKIP/);
  assert.match(result.stdout, /compatibility\/claude: SKIP - planned target not installed/);
  assert.match(result.stdout, /compatibility\/copilot: SKIP - planned target not installed/);
  assert.match(result.stdout, /compatibility\/opencode: SKIP - experimental target not installed/);
});

test('multi-target sync updates installed targets in stable order', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);
  await execCli(repoRoot, ['install', '--agent', 'codex']);
  await execCli(repoRoot, ['install', '--agent', 'claude']);
  await execCli(repoRoot, ['install', '--agent', 'copilot']);
  await execCli(repoRoot, ['install', '--agent', 'opencode']);

  await writeCanonical(repoRoot, '.prodify/AGENTS.md', '# Shared Canonical\n');
  await writeCanonical(repoRoot, '.prodify/project.md', '# Project\n\nShared project context.\n');

  const result = await execCli(repoRoot, ['sync']);
  const lines = result.stdout.trim().split('\n');

  assert.equal(result.exitCode, 0);
  assert.deepEqual(lines, [
    `sync claude: updated ${path.join(repoRoot, 'CLAUDE.md')}`,
    `sync codex: updated ${path.join(repoRoot, 'AGENTS.md')}`,
    `sync copilot: updated ${path.join(repoRoot, '.github', 'copilot-instructions.md')}`,
    `sync opencode: updated ${path.join(repoRoot, '.opencode', 'AGENTS.md')}`
  ]);
});

test('doctor reports mixed healthy and drifted installed targets', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);
  await execCli(repoRoot, ['install', '--agent', 'codex']);
  await execCli(repoRoot, ['install', '--agent', 'claude']);

  const claudePath = path.join(repoRoot, 'CLAUDE.md');
  const drifted = (await fs.readFile(claudePath, 'utf8')).replace('Prodify Canonical Instructions', 'Drifted Claude');
  await fs.writeFile(claudePath, drifted, 'utf8');

  const result = await execCli(repoRoot, ['doctor']);

  assert.equal(result.exitCode, 1);
  assert.match(result.stdout, /compatibility\/codex: PASS/);
  assert.match(result.stdout, /compatibility\/claude: PASS/);
  assert.match(result.stdout, /drift\/CLAUDE\.md: FAIL/);
});
