import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';

import { runCli } from '../../src/cli.js';
import { createTempRepo, memoryStream } from '../unit/helpers.js';

async function execCli(repoRoot, args) {
  const stdout = memoryStream();
  const stderr = memoryStream();
  const exitCode = await runCli(args, { cwd: repoRoot, stdout, stderr });

  return {
    exitCode,
    stdout: stdout.toString(),
    stderr: stderr.toString()
  };
}

test('happy path covers init, install codex, sync, and doctor', async () => {
  const repoRoot = await createTempRepo();

  let result = await execCli(repoRoot, ['init']);
  assert.equal(result.exitCode, 0);
  assert.equal(await fs.readFile(path.join(repoRoot, '.prodify', 'version.json'), 'utf8').then(Boolean), true);
  assert.equal(await fs.stat(path.join(repoRoot, '.prodify', 'AGENTS.md')).then(() => true), true);
  await assert.rejects(fs.access(path.join(repoRoot, 'AGENTS.md')));

  result = await execCli(repoRoot, ['install', '--agent', 'codex']);
  assert.equal(result.exitCode, 0);
  const installedAgents = await fs.readFile(path.join(repoRoot, 'AGENTS.md'), 'utf8');
  assert.match(installedAgents, /Generated by Prodify\./);

  result = await execCli(repoRoot, ['sync']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /codex: unchanged/);

  result = await execCli(repoRoot, ['doctor']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /canonical: PASS/);
  assert.match(result.stdout, /compatibility\/codex: PASS/);
});

test('existing unmanaged root AGENTS.md blocks codex install', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);
  await fs.writeFile(path.join(repoRoot, 'AGENTS.md'), '# unmanaged\n', 'utf8');

  const result = await execCli(repoRoot, ['install', '--agent', 'codex']);

  assert.equal(result.exitCode, 1);
  assert.match(result.stderr, /not Prodify-managed/);
});

test('install succeeds when root AGENTS.md is already managed', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  let result = await execCli(repoRoot, ['install', '--agent', 'codex']);
  assert.equal(result.exitCode, 0);

  result = await execCli(repoRoot, ['install', '--agent', 'codex']);
  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /Installed codex compatibility file/);
});

test('managed file updates after canonical AGENTS change', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);
  await execCli(repoRoot, ['install', '--agent', 'codex']);
  await fs.writeFile(path.join(repoRoot, '.prodify', 'AGENTS.md'), '# Updated Canonical\n', 'utf8');

  const result = await execCli(repoRoot, ['sync']);
  const updated = await fs.readFile(path.join(repoRoot, 'AGENTS.md'), 'utf8');

  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /codex: updated/);
  assert.match(updated, /# Updated Canonical/);
});

test('sync does not overwrite unmanaged files', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);
  await fs.writeFile(path.join(repoRoot, 'AGENTS.md'), '# unmanaged\n', 'utf8');

  const before = await fs.readFile(path.join(repoRoot, 'AGENTS.md'), 'utf8');
  const result = await execCli(repoRoot, ['sync']);
  const after = await fs.readFile(path.join(repoRoot, 'AGENTS.md'), 'utf8');

  assert.equal(result.exitCode, 0);
  assert.equal(before, after);
  assert.match(result.stdout, /codex: skipped-unmanaged/);
});

test('repeat sync produces no diffs', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);
  await execCli(repoRoot, ['install', '--agent', 'codex']);

  const before = await fs.readFile(path.join(repoRoot, 'AGENTS.md'), 'utf8');
  const result = await execCli(repoRoot, ['sync']);
  const after = await fs.readFile(path.join(repoRoot, 'AGENTS.md'), 'utf8');

  assert.equal(result.exitCode, 0);
  assert.equal(before, after);
  assert.match(result.stdout, /codex: unchanged/);
});

test('init fails when .prodify already exists', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  const result = await execCli(repoRoot, ['init']);

  assert.equal(result.exitCode, 1);
  assert.match(result.stderr, /\.prodify\/ already exists/);
});

test('doctor reports drift for managed AGENTS', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);
  await execCli(repoRoot, ['install', '--agent', 'codex']);
  await fs.writeFile(path.join(repoRoot, 'AGENTS.md'), '<!--\nGenerated by Prodify.\nTarget agent: codex\nCanonical source: .prodify/AGENTS.md\nRegenerate with: prodify sync --agent codex\nManual edits may be overwritten.\n-->\n\n# Drifted\n', 'utf8');

  const result = await execCli(repoRoot, ['doctor']);

  assert.equal(result.exitCode, 1);
  assert.match(result.stdout, /drift\/AGENTS\.md: FAIL/);
});

test('doctor fails when canonical AGENTS is missing', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);
  await fs.rm(path.join(repoRoot, '.prodify', 'AGENTS.md'));

  const result = await execCli(repoRoot, ['doctor']);

  assert.equal(result.exitCode, 1);
  assert.match(result.stdout, /canonical: FAIL/);
});

test('planned and experimental targets fail clearly but remain recognized', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  const claude = await execCli(repoRoot, ['install', '--agent', 'claude']);
  const copilot = await execCli(repoRoot, ['install', '--agent', 'copilot']);
  const opencode = await execCli(repoRoot, ['install', '--agent', 'opencode']);

  assert.equal(claude.exitCode, 1);
  assert.equal(copilot.exitCode, 1);
  assert.equal(opencode.exitCode, 1);
  assert.match(claude.stderr, /planned but not yet enabled/);
  assert.match(copilot.stderr, /planned but not yet enabled/);
  assert.match(opencode.stderr, /experimental and not yet enabled/);
});
