import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';

import { runCli } from '../../src/cli.js';
import { bootstrapFlowState, startFlowExecution } from '../../src/core/flow-state.js';
import { readRuntimeState, writeRuntimeState } from '../../src/core/state.js';
import { createTempRepo, memoryStream } from '../unit/helpers.js';

const TARGET_PATHS = {
  codex: 'AGENTS.md',
  claude: 'CLAUDE.md',
  copilot: '.github/copilot-instructions.md',
  opencode: '.opencode/AGENTS.md'
};

async function execCli(repoRoot, args) {
  const stdout = memoryStream();
  const stderr = memoryStream();
  const exitCode = await runCli(args, { cwd: repoRoot, stdout, stderr });

  return {
    exitCode,
    stdout: stdout.toString(),
    stderr: stderr.toString()
  };
}

async function readRepoFile(repoRoot, relativePath) {
  return fs.readFile(path.join(repoRoot, relativePath), 'utf8');
}

test('status reports an uninitialized repo cleanly', async () => {
  const repoRoot = await createTempRepo();

  const result = await execCli(repoRoot, ['status']);

  assert.equal(result.exitCode, 1);
  assert.match(result.stdout, /Repository: not initialized/);
  assert.match(result.stdout, /Recommended next action: prodify init/);
});

test('init creates canonical runtime scaffolding and managed agent adapters', async () => {
  const repoRoot = await createTempRepo();

  const result = await execCli(repoRoot, ['init']);

  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /Initialized Prodify/);
  assert.match(result.stdout, /Prepared runtime adapters/);
  await fs.access(path.join(repoRoot, '.prodify', 'state.json'));
  await fs.access(path.join(repoRoot, '.prodify', 'runtime-commands.md'));

  for (const relativePath of Object.values(TARGET_PATHS)) {
    const content = await readRepoFile(repoRoot, relativePath);
    assert.match(content, /Generated by Prodify\./);
    assert.match(content, /\$prodify-init/);
  }
});

test('status becomes the primary user-facing summary after init', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  const result = await execCli(repoRoot, ['status']);

  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /Canonical files: healthy/);
  assert.match(result.stdout, /Version\/schema: current/);
  assert.match(result.stdout, /Primary agent runtime: none/);
  assert.match(result.stdout, /Execution state: not bootstrapped/);
  assert.match(result.stdout, /Recommended next action: open your agent and run \$prodify-init/);
});

test('doctor validates healthy setup after init', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  const result = await execCli(repoRoot, ['doctor']);

  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /canonical: PASS/);
  assert.match(result.stdout, /canonical\/schema: PASS/);
  assert.match(result.stdout, /runtime\/state: PASS/);
  assert.match(result.stdout, /compatibility\/codex: PASS/);
  assert.match(result.stdout, /compatibility\/claude: PASS/);
  assert.match(result.stdout, /compatibility\/copilot: PASS/);
  assert.match(result.stdout, /compatibility\/opencode: PASS/);
});

test('update is a no-op refresh on a current repo', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  const result = await execCli(repoRoot, ['update']);

  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /Prodify Update/);
  assert.match(result.stdout, /Version\/schema: current/);
  assert.match(result.stdout, /Canonical assets: /);
  assert.match(result.stdout, /Generated adapters: /);
});

test('update repairs outdated version metadata and restores managed assets', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  await fs.writeFile(path.join(repoRoot, '.prodify', 'version.json'), '{\n  "schema_version": "1",\n  "preset_name": "default",\n  "preset_version": "1.0.0"\n}\n', 'utf8');
  await fs.rm(path.join(repoRoot, '.prodify', 'runtime-commands.md'));

  const result = await execCli(repoRoot, ['update']);

  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /Version\/schema: outdated/);
  await fs.access(path.join(repoRoot, '.prodify', 'runtime-commands.md'));
});

test('update preserves user-owned canonical files', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  await fs.writeFile(path.join(repoRoot, '.prodify', 'AGENTS.md'), '# Canonical\n\nCustom operator guidance.\n', 'utf8');
  await fs.writeFile(path.join(repoRoot, '.prodify', 'project.md'), '# Project\n\nCustom project context.\n', 'utf8');

  const result = await execCli(repoRoot, ['update']);

  assert.equal(result.exitCode, 0);
  assert.match(await readRepoFile(repoRoot, '.prodify/AGENTS.md'), /Custom operator guidance/);
  assert.match(await readRepoFile(repoRoot, '.prodify/project.md'), /Custom project context/);
  assert.match(await readRepoFile(repoRoot, 'AGENTS.md'), /Custom operator guidance/);
});

test('status reports malformed runtime state and recommends update', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);
  await fs.writeFile(path.join(repoRoot, '.prodify', 'state.json'), '{bad json\n', 'utf8');

  const result = await execCli(repoRoot, ['status']);

  assert.equal(result.exitCode, 1);
  assert.match(result.stdout, /Runtime state: Runtime state is malformed/);
  assert.match(result.stdout, /Recommended next action: prodify update/);
});

test('runtime bootstrap and resume readiness are reflected in status', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  const initial = await readRuntimeState(repoRoot, {
    presetMetadata: {
      name: 'default',
      version: '2.0.0',
      schemaVersion: '2'
    }
  });
  const bootstrapped = bootstrapFlowState(initial, {
    agent: 'codex',
    mode: 'interactive'
  });
  const running = startFlowExecution(bootstrapped);
  await writeRuntimeState(repoRoot, running);

  const result = await execCli(repoRoot, ['status']);

  assert.equal(result.exitCode, 0);
  assert.match(result.stdout, /Primary agent runtime: codex/);
  assert.match(result.stdout, /Execution state: running at understand \(01-understand\)/);
  assert.match(result.stdout, /Resumable: yes/);
  assert.match(result.stdout, /Recommended next action: \$prodify-resume/);
});

test('generated runtime instructions cover all supported targets', async () => {
  const repoRoot = await createTempRepo();
  await execCli(repoRoot, ['init']);

  for (const relativePath of Object.values(TARGET_PATHS)) {
    const content = await readRepoFile(repoRoot, relativePath);
    assert.match(content, /\$prodify-init/);
    assert.match(content, /\$prodify-execute/);
    assert.match(content, /\$prodify-resume/);
  }
});

test('README and help output match the lifecycle model', async () => {
  const repoRoot = await createTempRepo();
  const readme = await fs.readFile(path.join(process.cwd(), 'README.md'), 'utf8');
  const help = await execCli(repoRoot, ['--help']);

  assert.match(readme, /prodify status/);
  assert.match(readme, /\$prodify-init/);
  assert.doesNotMatch(readme, /prodify install --agent/);
  assert.match(help.stdout, /prodify status/);
  assert.match(help.stdout, /prodify update/);
  assert.doesNotMatch(help.stdout, /prodify install/);
});
