import { KNOWN_TARGETS } from './paths.js';

const HEADER_START = '<!--';
const HEADER_END = '-->';

export function renderCanonicalSourceList(sourcePaths) {
  return [...sourcePaths].sort().join(', ');
}

export function parseManagedFileHeader(content) {
  if (!content.startsWith(HEADER_START)) {
    return null;
  }

  const endIndex = content.indexOf(HEADER_END);
  if (endIndex === -1) {
    return null;
  }

  const rawHeader = content.slice(HEADER_START.length, endIndex).trim();
  const lines = rawHeader.split('\n').map((line) => line.trim()).filter(Boolean);

  const metadata = {};

  for (const line of lines) {
    if (line === 'Generated by Prodify.') {
      metadata.generatedByProdify = true;
      continue;
    }

    const separatorIndex = line.indexOf(':');
    if (separatorIndex === -1) {
      if (line === 'Manual edits may be overwritten.') {
        metadata.manualEditsWarning = true;
      }

      continue;
    }

    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim();
    metadata[key] = value;
  }

  if (!metadata.generatedByProdify) {
    return null;
  }

  const targetAgent = metadata['Target agent'];
  const canonicalSource = metadata['Canonical source'];
  const regenerateWith = metadata['Regenerate with'];

  if (!targetAgent || !KNOWN_TARGETS.includes(targetAgent) || !canonicalSource || !regenerateWith) {
    return null;
  }

  return {
    targetAgent,
    canonicalSources: canonicalSource.split(',').map((item) => item.trim()).filter(Boolean),
    regenerateWith,
    manualEditsWarning: Boolean(metadata.manualEditsWarning),
    headerLength: endIndex + HEADER_END.length
  };
}

export function isManagedFileContent(content) {
  return parseManagedFileHeader(content) !== null;
}
