import crypto from 'node:crypto';
import { isRuntimeProfileName } from './paths.js';
import type { ManagedFileHeader, ManagedFileState } from '../types.js';

const HEADER_START = '<!--';
const HEADER_END = '-->';

export function renderCanonicalSourceList(sourcePaths: readonly string[]): string {
  return [...sourcePaths].sort().join(', ');
}

export function parseManagedFileHeader(content: string): ManagedFileHeader | null {
  if (!content.startsWith(HEADER_START)) {
    return null;
  }

  const endIndex = content.indexOf(HEADER_END);
  if (endIndex === -1) {
    return null;
  }

  const rawHeader = content.slice(HEADER_START.length, endIndex).trim();
  const lines = rawHeader.split('\n').map((line) => line.trim()).filter(Boolean);

  const metadata: Record<string, string | boolean> = {};

  for (const line of lines) {
    if (line === 'Generated by Prodify.') {
      metadata.generatedByProdify = true;
      continue;
    }

    const separatorIndex = line.indexOf(':');
    if (separatorIndex === -1) {
      if (line === 'Manual edits may be overwritten.') {
        metadata.manualEditsWarning = true;
      }

      continue;
    }

    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim();
    metadata[key] = value;
  }

  if (metadata.generatedByProdify !== true) {
    return null;
  }

  const targetAgent = metadata['Target agent'];
  const canonicalSource = metadata['Canonical source'];
  const regenerateWith = metadata['Regenerate with'];
  const bodyFingerprint = metadata['Body fingerprint'];

  if (
    typeof targetAgent !== 'string'
    || !isRuntimeProfileName(targetAgent)
    || typeof canonicalSource !== 'string'
    || typeof regenerateWith !== 'string'
  ) {
    return null;
  }

  return {
    targetAgent,
    canonicalSources: canonicalSource.split(',').map((item: string) => item.trim()).filter(Boolean),
    regenerateWith,
    bodyFingerprint: typeof bodyFingerprint === 'string' ? bodyFingerprint : null,
    manualEditsWarning: metadata.manualEditsWarning === true,
    headerLength: endIndex + HEADER_END.length
  };
}

export function isManagedFileContent(content: string): boolean {
  return parseManagedFileHeader(content) !== null;
}

export function extractManagedBody(content: string, headerLength: number): string {
  let body = content.slice(headerLength);

  if (body.startsWith('\r\n\r\n')) {
    return body.slice(4);
  }

  if (body.startsWith('\n\n')) {
    return body.slice(2);
  }

  if (body.startsWith('\r\n')) {
    return body.slice(2);
  }

  if (body.startsWith('\n')) {
    return body.slice(1);
  }

  return body;
}

export function computeBodyFingerprint(body: string): string {
  return crypto.createHash('sha256').update(body, 'utf8').digest('hex');
}

export function detectManagedFileState(existingContent: string, expectedContent: string): ManagedFileState {
  const existingHeader = parseManagedFileHeader(existingContent);
  if (!existingHeader) {
    return {
      state: 'unmanaged',
      header: null
    };
  }

  const expectedHeader = parseManagedFileHeader(expectedContent);
  const currentBody = extractManagedBody(existingContent, existingHeader.headerLength);
  const currentFingerprint = computeBodyFingerprint(currentBody);

  if (existingHeader.bodyFingerprint && existingHeader.bodyFingerprint !== currentFingerprint) {
    return {
      state: 'conflict',
      header: existingHeader
    };
  }

  if (existingContent === expectedContent) {
    return {
      state: 'unchanged',
      header: existingHeader
    };
  }

  return {
    state: 'outdated',
    header: expectedHeader ?? existingHeader
  };
}
