import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';

import { generateCodexContent } from '../../dist/generators/codex.js';
import { createTempRepo } from './helpers.js';

test('codex generator prepends header and preserves body', async () => {
  const repoRoot = await createTempRepo();
  await fs.mkdir(path.join(repoRoot, '.prodify'), { recursive: true });
  await fs.writeFile(path.join(repoRoot, '.prodify', 'AGENTS.md'), '# Canonical\nBody\n', 'utf8');
  await fs.writeFile(path.join(repoRoot, '.prodify', 'runtime-commands.md'), '# Runtime Commands\n\nRun `$prodify-init`.\n', 'utf8');

  const output = await generateCodexContent(repoRoot);

  assert.match(output, /Generated by Prodify\./);
  assert.match(output, /Regenerate with: prodify update/);
  assert.match(output, /# Canonical\nBody\n/);
  assert.match(output, /# Runtime Commands/);
  assert.match(output, /\$prodify-init/);
});

test('codex generation is deterministic', async () => {
  const repoRoot = await createTempRepo();
  await fs.mkdir(path.join(repoRoot, '.prodify'), { recursive: true });
  await fs.writeFile(path.join(repoRoot, '.prodify', 'AGENTS.md'), '# Canonical\nBody\n', 'utf8');
  await fs.writeFile(path.join(repoRoot, '.prodify', 'runtime-commands.md'), '# Runtime Commands\n\nRun `$prodify-init`.\n', 'utf8');

  const first = await generateCodexContent(repoRoot);
  const second = await generateCodexContent(repoRoot);

  assert.equal(first, second);
});

test('codex generator fails when canonical source is missing', async () => {
  const repoRoot = await createTempRepo();
  await fs.mkdir(path.join(repoRoot, '.prodify'), { recursive: true });

  await assert.rejects(
    generateCodexContent(repoRoot),
    /Canonical source is missing/
  );
});
