import test from 'node:test';
import assert from 'node:assert/strict';

import { parseManagedFileHeader } from '../../src/core/managed-files.js';
import { renderManagedFileHeader } from '../../src/generators/header.js';

test('header renders correctly for codex', () => {
  const header = renderManagedFileHeader({
    agent: 'codex',
    canonicalSources: ['.prodify/AGENTS.md'],
    regenerateCommand: 'prodify sync --agent codex'
  });

  assert.match(header, /Generated by Prodify\./);
  assert.match(header, /Target agent: codex/);
  assert.match(header, /Canonical source: \.prodify\/AGENTS\.md/);
});

test('managed file detection works for valid header', () => {
  const content = `${renderManagedFileHeader({
    agent: 'codex',
    canonicalSources: ['.prodify/AGENTS.md'],
    regenerateCommand: 'prodify sync --agent codex'
  })}\n\n# Body\n`;

  const parsed = parseManagedFileHeader(content);
  assert.equal(parsed.targetAgent, 'codex');
  assert.deepEqual(parsed.canonicalSources, ['.prodify/AGENTS.md']);
});

test('managed file detection returns null when header is missing', () => {
  assert.equal(parseManagedFileHeader('# plain file\n'), null);
});
