import test from 'node:test';
import assert from 'node:assert/strict';

import { computeBodyFingerprint, detectManagedFileState, parseManagedFileHeader } from '../../dist/core/managed-files.js';
import { renderManagedFileHeader } from '../../dist/generators/header.js';

test('header renders correctly for codex', () => {
  const bodyFingerprint = computeBodyFingerprint('# Body\n');
  const header = renderManagedFileHeader({
    agent: 'codex',
    canonicalSources: ['.prodify/AGENTS.md'],
    regenerateCommand: 'prodify update',
    bodyFingerprint
  });

  assert.match(header, /Generated by Prodify\./);
  assert.match(header, /Target agent: codex/);
  assert.match(header, /Canonical source: \.prodify\/AGENTS\.md/);
  assert.match(header, /Body fingerprint:/);
});

test('managed file detection works for valid header', () => {
  const bodyFingerprint = computeBodyFingerprint('# Body\n');
  const content = `${renderManagedFileHeader({
    agent: 'codex',
    canonicalSources: ['.prodify/AGENTS.md'],
    regenerateCommand: 'prodify update',
    bodyFingerprint
  })}\n\n# Body\n`;

  const parsed = parseManagedFileHeader(content);
  assert.equal(parsed.targetAgent, 'codex');
  assert.deepEqual(parsed.canonicalSources, ['.prodify/AGENTS.md']);
  assert.equal(parsed.bodyFingerprint, bodyFingerprint);
});

test('managed file detection returns null when header is missing', () => {
  assert.equal(parseManagedFileHeader('# plain file\n'), null);
});

test('managed file state detects manual-edit conflicts', () => {
  const body = '# Body\n';
  const expected = `${renderManagedFileHeader({
    agent: 'codex',
    canonicalSources: ['.prodify/AGENTS.md'],
    regenerateCommand: 'prodify update',
    bodyFingerprint: computeBodyFingerprint(body)
  })}\n\n${body}`;
  const drifted = expected.replace('# Body', '# Drifted');

  const state = detectManagedFileState(drifted, expected);
  assert.equal(state.state, 'conflict');
});
